### ISSUE TITLE
User ID

### ISSUE THREAD

**Issue by scratchyone** [philliphenslee/smartslack#1]
How could I get a user name from a user ID, and a user id from a username? The getUser function returns null. Thanks!

**Comment by philliphenslee** [comment]
If using a username it would look something like this....

client.users.getUser('phil', function (err, result) {
        console.log(result.id);
    });

**Comment by scratchyone** [comment]
Thanks! How would I get a name from an id?

**Comment by philliphenslee** [comment]
The same way, like this...

client.users.getUser('U0BC6D9V1', function (err, result) {
console.log(result.name);
});

**Comment by philliphenslee** [comment]
If you will log the entire result variable you can see the data that is accessible using result.fieldname

Hope this helps...

**Comment by scratchyone** [comment]
Thanks! Great job on this module. I will close this unless I have any issues

**Comment by philliphenslee** [comment]
Thanks for the feedback and glad I could help.

**Comment by scratchyone** [comment]
Hmm. 
```
client.users.getUser('U0BC6D9V1', function (err, result) {
console.log(result.name);
});
```
returns result as null

**Comment by philliphenslee** [comment]
Form your room?  

Write client.users to the console and see if you see your userid in the output. 

Example:

var client = new SmartSlack(options);

// Login to Slack
client.start();

client.on('connected', function () {
    client.users.getUser('U0BC6D9V1', function (err, result) {
        console.log(result);
        **console.log(client.users);**
    });

**Comment by scratchyone** [comment]
That worked!

**Comment by scratchyone** [comment]
Thanks!

**Comment by scratchyone** [comment]
It seems like the user IDs I used were invalid.

**Comment by philliphenslee** [comment]
Are you may have been calling it before the data was available in the cache. Glad you got it working.

**Comment by scratchyone** [comment]
It looks like I was looking for message.use, instead of message.bot_id
