### ISSUE TITLE
Executing Commands?

### ISSUE THREAD

**Issue by scratchyone** [philliphenslee/smartslack#3]
Is it possible to have my bot execute a command (/kick)? Will it have the same access to commands that I do? Thanks!

**Comment by philliphenslee** [comment]
I am not sure exactly what you are trying to do, but you may have to fork that into another process based on the bots response to something?

**Comment by scratchyone** [comment]
I was trying to figure out how to have the bot execute a command, so it could kick users using "/kick" or invite users with "/invite", but it seems like only real users can do that, so currently I am just accessing the api directly.
