### ISSUE TITLE
Regexp token slackbot invalid

### ISSUE THREAD

**Issue by josephbedminster** [philliphenslee/smartslack#4]
Hi,
I'm using your package, and my slack-token is : 
xxxx-000000000000-000000000000000000000000
It doesn't match with regexp in index.js line 40 : 
` if (typeof accessToken !== 'string' || !accessToken.match(/^([a-z]{4})-([0-9]{11})-([0-9a-zA-Z]{24})$/)) {`
Token may be 11 or 12 characters long in the middle, like  : 
`/^([a-z]{4})-([0-9]{11,12})-([0-9a-zA-Z]{24})$/`

**Comment by philliphenslee** [comment]
This is a little delayed, but thanks for finding this. A the time of development I could not find solid documentation on the specifics of the token format. Code updated and released v.1.2.1 with the fix.
