### ISSUE TITLE
Slack Token Format - Invalid Token

### ISSUE THREAD

**Issue by webstercharly** [philliphenslee/smartslack#5]
I tried to open up a pull request but do not have the  permissions.
Sorry in advance, my regex ability is awful which is why I copied the original regex and added digits 
`-([0-9]{10})`

lib/index.js
```
if (typeof accessToken !== 'string'
      || !accessToken.match(/^([a-z]{4})-([0-9]{11,12})-([0-9a-zA-Z]{24})$/)
      && !accessToken.match(/^([a-z]{4})-([0-9]{10})-([0-9]{11,12})-([0-9a-zA-Z]{24})$/)
    ) {
        throw new Error(errors.invalid_token);
    }
```

index.spec.js
```
var mockopts_new_token =
{
    token: 'xxxx-0123456789-01234567890-ABCDEFGHIJKLMNOPQRSTUVWX',
   autoReconnect: false
};

it('can be constructed with new token format', function (done) {
  var slackClient = new SmartSlack(mockopts_new_token);
  slackClient.should.be.an('object');
  done();
});
```

**Comment by philliphenslee** [comment]
Hey webstercharly,

I will try to get this fixed ASAP. Slack has made many changes to the API since I started this project four years ago. I am sure there is a long list of improvements if you want to contribute. Thanks for identifying this one. 

Phil

**Comment by philliphenslee** [comment]
Issue with regex and new token format has been addressed.

**Comment by webstercharly** [comment]
Thank you Phillip. I did try to open a new branch to create a PR however it wouldn’t allow me to push to the remote branch.
